server:
  port: 10000

spring:
  # --- Konfiguracja Bazy Danych dla Render.com ---
  datasource:
    # POPRAWKA: Ręcznie dodajemy "jdbc:" przed adresem z Render,
    # aby stworzyć poprawny JDBC URL.
    url: jdbc:${DATABASE_URL}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
  # --- Konfiguracja JPA/Hibernate ---
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  # --- Konfiguracja Spring MVC ---
  mvc:
    hiddenmethod:
      filter:
        enabled: true