server:
  port: 10000

spring:
  # --- Konfiguracja Bazy Danych dla Render.com ---
  datasource:
    # Render dostarcza pełny adres URL w zmiennej DATABASE_URL.
    # Spring Boot jest wystarczająco inteligentny, aby wyciągnąć z niego
    # sterownik, użytkownika, hasło i adres bazy danych.
    url: ${DATABASE_URL}

  # --- Konfiguracja JPA/Hibernate ---
  jpa:
    hibernate:
      # WAŻNE: Zmieniono z "create-drop" na "update".
      # "create-drop" KASUJE całą bazę danych przy każdym restarcie aplikacji.
      # "update" będzie tylko aktualizować schemat, jeśli wykryje zmiany w encjach.
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        # Ta właściwość jest przydatna do debugowania
        format_sql: true
        # Dialekt jest ważny, aby Hibernate wiedział, jakiego SQL używać
        dialect: org.hibernate.dialect.MySQLDialect

  # --- Konfiguracja Spring MVC ---
  mvc:
    hiddenmethod:
      filter:
        enabled: true