server:
  port: 10000

spring:
  # --- Konfiguracja Bazy Danych dla Render.com ---
  datasource:
    url: jdbc:${DATABASE_URL}
    # DODAJ TĘ LINIJKĘ:
    driver-class-name: com.mysql.cj.jdbc.Driver

  # --- Konfiguracja JPA/Hibernate ---
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  # --- Konfiguracja Spring MVC ---
  mvc:
    hiddenmethod:
      filter:
        enabled: true