spring:
  datasource:
    url: jdbc:mysql://localhost:3306/magazyn2
    username: root
    password: root

  jpa:
    database: mysql
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never
      data-locations: classpath:data.sql
  mvc:
    hiddenmethod:
      filter:
        enabled: true