spring:
  datasource:
    # Doklejamy "jdbc:" do zmiennej DATABASE_URL dostarczonej przez Render
    url: jdbc:${DATABASE_URL}
  jpa:
    # Ta sekcja pomaga Hibernate poprawnie rozpoznać dialekt bazy danych
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update # lub inna strategia, np. 'validate'