server:
  port: 10000

spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/magazyn2}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}

  jpa:
    database: mysql
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true